name: Go Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Display Go version
      run: go version

    - name: Install dependencies
      run: make setup

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest
        golangci-lint --version

    - name: Install gofumpt
      run: go install mvdan.cc/gofumpt@latest

    - name: Run tests
      run: make test

    - name: Run linter
      run: make lint

    - name: Generate coverage report
      run: make coverage

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: matsuren/jqcompletion
